<!doctype html>
<html ng-app="myApp">
    <head>
        <meta charset="UTF-8" />
        <title>ZF2+Angular</title>
        <link href="css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div id="wrap">
            <div class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toogle="collapse" data-target=".navbar">
                            <span class="sr-only">Toogle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">School of Net</a>
                    </div>    
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="#/categorias">Categorias</a></li>
                            <li><a href="#/produtos">Produtos</a></li>                        
                        </ul>
                    </div>
                </div>
            </div> 

            <?= $this->content; ?>
            
            <br />
            Apigility By Zend framework (VIDE)
            <br />
                        
            <div id="footer">
                <div class="container">
                    <p class="text-muted credit">School of Net.</p>                        
                </div>
            </div>  

        </div>

        <br />        
        <!--
        <div ng-controller="CtrlApp">
            <input type="text" ng_model="nome" />
            <h1>{{nome}}</h1>
        </div>
        <script>
            var CtrlApp = function($scope) {
                $scope.nome = "Jonathan";
            }
        </script>
        -->

        <!--
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script> var $jQuery = jQuery.noConflict();</script>         
        -->
        
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular-route.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular-resource.min.js"></script>
        <script src="projetoangular/app.js"></script>
        <script src="projetoangular/controllers.js"></script>
        <script src="projetoangular/services.js"></script>
    </body>
</html>



