<br />
<br />

<h1>Categorias</h1> 

<ul>
    <?php foreach ($categorias as $categoria): ?>
        <li><?php echo $categoria->getNome(); ?></li>
    <?php endforeach; ?>
</ul>


<!--
<div class="container" ng-controller="CategoriasCtrl">
-->
<div class="container">
    <div class="page-header">
        <br />
        <div ng-view></div>
        <!--<h1>{{nome}}</h1>-->                    
    </div>       
</div>